# Prometheus main config for thesis

global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # Prometheus itself (optional)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # MongoDB Exporter
  - job_name: "mongodb"
    static_configs:
      - targets: ["localhost:9216"]

  # PostgreSQL Exporter
  - job_name: "postgres"
    static_configs:
      - targets: ["localhost:9187"]

  # Flink JobManager
  - job_name: "flink_jobmanager"
    static_configs:
      - targets: ["localhost:9250"]

  # Flink TaskManager
  - job_name: "flink_taskmanager"
    static_configs:
      - targets: ["localhost:9251"]

  # Kafka Exporter
  - job_name: "kafka"
    static_configs:
      - targets: ["localhost:9308"]

